services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: vacation
      POSTGRES_PASSWORD: vacation123
      POSTGRES_DB: vacation_tracker
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://vacation:vacation123@postgres:5432/vacation_tracker
      - PYTHONPATH=/app:/app/src # Added /app/src to Python path
    depends_on:
      - postgres
    command: >
      sh -c "
        sleep 3 &&
        cd /app &&
        alembic upgrade head &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      # - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  frontend_node_modules:
  postgres_data:
